version: 2
jobs:

  check-formatting:
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.394
    steps:
      - checkout
      - restore_cache:
          key: atlassian-connect-crux-formatting-cp-{{ checksum "deps.edn" }}-{{ arch }}
      - run: clojure -A:lint
      - save_cache:
          paths:
            - /home/circleci/.cpcache
            - /home/circleci/.gitlibs
            - /home/circleci/.m2
          key: atlassian-connect-crux-formatting-cp-{{ checksum "deps.edn" }}-{{ arch }}

  build:
    docker:
      - image: circleci/clojure:tools-deps-1.9.0.394
    steps:
      - checkout
      - run: mkdir -p test-results/kaocha
      - run: bin/kaocha --plugin kaocha.plugin/junit-xml --junit-xml-file test-results/kaocha/results.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: target/coverage

workflows:
  version: 2
  build-n-test:
    jobs:
        - check-formatting
        - build:
            requires:
              - check-formatting
